export const API_ENDPOINTS: Record<string, string> = {
  PRODUCTS: 'api/products',
  SETTINGS: 'api/settings',
  CUSTOMER: 'api/customers/me',
  CUSTOMERS: 'api/customers/me',
  COUPONS: 'api/coupons',
  CATEGORY: 'api/categories',
  PARENT_CATEGORIES: 'api/categories',
  TYPE: 'api/types',
  ORDERS: 'api/orders',
  LOGIN: 'auth/jwt/create',
  UPDATE_CONTACT: 'api/customers/phone',
  REGISTER: 'auth/users',
  FORGET_PASSWORD: 'request-reset-email/',
  LOGOUT: 'logout',
  CHANGE_PASSWORD: 'change-password',
  RESET_PASSWORD: 'password-reset-complete',
  VERIFY_FORGET_PASSWORD: 'verify-token/',
  ADDRESS: 'api/address',
  ORDER: 'tracking-number',
};
