# Generated by Django 3.2.9 on 2021-11-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(blank=True, max_length=1024, null=True)),
                ('original', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
